# Generated by Django 3.2.9 on 2022-04-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='anonymous', max_length=20, verbose_name='Name')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
